export const JUZ_QUOTES: Record<number, { ar: string; en: string }> = {
  1: { ar: "«الم ذَلِكَ الْكِتَابُ لاَ رَيْبَ فِيهِ» بداية مباركة لرحلة النور! 🌸", en: "«This is the Book about which there is no doubt» A blessed start to your journey of light! 🌸" },
  2: { ar: "«فَاذْكُرُونِي أَذْكُرْكُمْ» ما أجمل أن تعيش الورد وأنت في ذكر الله! 🌟", en: "«So remember Me; I will remember you» How beautiful to live your Khatmah in the remembrance of Allah! 🌟" },
  3: { ar: "«اللّهُ لاَ إِلَـهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ» آية الكرسي درعك، أتممت الجزء الثالث بنجاح! ✨", en: "«Allah - there is no deity except Him, the Ever-Living, the Sustainer of [all] existence» Ayatul Kursi is your shield! ✨" },
  4: { ar: "«لَن تَنَالُواْ الْبِرَّ حَتَّى تُنفِقُواْ مِمَّا تُحِبُّونَ» لقد قدمت وقتك للقرآن، وهذا أعظم الإنفاق! 🤲", en: "«Never will you attain the good [reward] until you spend [in the way of Allah] from that which you love» You gave your time to the Quran! 🤲" },
  5: { ar: "«وَالْمُحْصَنَاتُ مِنَ النِّسَاءِ» أتممت الجزء الخامس، زادك الله فهماً ورزقك العمل بما تقرأ 🌹", en: "Completed the 5th Juz, may Allah increase your understanding and action upon what you read 🌹" },
  6: { ar: "«لاَ يُحِبُّ اللّهُ الْجَهْرَ بِالسُّوَءِ مِنَ الْقَوْلِ» حفظ الله لسانك بالقرآن كما حفظت ورده! 🌺", en: "May Allah protect your tongue with the Quran as you preserved your daily target! 🌺" },
  7: { ar: "«وَإِذَا سَمِعُواْ مَا أُنزِلَ إِلَى الرَّسُولِ تَرَى أَعْيُنَهُمْ تَفِيضُ مِنَ الدَّمْعِ» جعل الله قلبك خاشعاً! 💧", en: "«And when they hear what has been revealed to the Messenger, you see their eyes overflowing with tears» May God make your heart humble! 💧" },
  8: { ar: "«وَلَوْ أَنَّ أَهْلَ الْقُرَى آمَنُواْ وَاتَّقَواْ لَفَتَحْنَا عَلَيْهِم بَرَكَاتٍ» بورك لك في وقتك وعمرك! 🌸", en: "May your time and life be blessed! 🌸" },
  9: { ar: "«قَالَ الْمَلأُ الَّذِينَ اسْتَكْبَرُواْ» رفعتك آيات الله المتواضعة، هنيئاً لك إتمام الجزء التاسع! 🌟", en: "Exalted by Allah's verses, congratulations on completing the ninth Juz! 🌟" },
  10: { ar: "«وَاعْلَمُواْ أَنَّمَا غَنِمْتُم مِّن شَيْءٍ» غنيمتك الكبرى هي القرآن، زادك الله من فضله! 💎", en: "Your greatest bounty is the Quran, may Allah increase you from His grace! 💎" },
  11: { ar: "«إِنَّمَا السَّبِيلُ عَلَى الَّذِينَ يَسْتَأْذِنُونَكَ وَهُمْ أَغْنِيَاء» أغناك الله بكلماته التامات! 🌿", en: "May Allah enrich you with His perfect words! 🌿" },
  12: { ar: "«وَمَا مِن دَآبَّةٍ فِي الأَرْضِ إِلاَّ عَلَى اللّهِ رِزْقُهَا» رزقك الله القرآن ولا يحرمك أجره! 🕊️", en: "«And there is no creature on earth but that upon Allah is its provision» May Allah grant you the Quran! 🕊️" },
  13: { ar: "«وَمَا أُبَرِّئُ نَفْسِي إِنَّ النَّفْسَ لأَمَّارَةٌ بِالسُّوءِ» روضت نفسك بالقرآن فأنار بصيرتك! 🤍", en: "You have disciplined your soul with the Quran, bringing light to your vision! 🤍" },
  14: { ar: "«الَر كِتَابٌ أَنزَلْنَاهُ إِلَيْكَ لِتُخْرِجَ النَّاسَ مِنَ الظُّلُمَاتِ إِلَى النُّورِ» نور على نور في الجزء الرابع عشر! ✨", en: "Light upon light in the fourteenth Juz! ✨" },
  15: { ar: "«سُبْحَانَ الَّذِي أَسْرَى بِعَبْدِهِ لَيْلاً» أسرى الله بقلبك في رياض آياته! 🕌", en: "May Allah take your heart on a journey through the gardens of His verses! 🕌" },
  16: { ar: "«قَالَ أَلَمْ أَقُل لَّكَ إِنَّكَ لَن تَسْتَطِيعَ مَعِي صَبْرًا» صبرت ونلت! منتصف الختمة قد اكتمل 🎉", en: "«Did I not tell you that with me you would never be able to have patience?» You were patient and succeeded! Half the Khatmah is complete 🎉" },
  17: { ar: "«اقْتَرَبَ لِلنَّاسِ حِسَابُهُمْ» جعل الله القرآن شفيعاً وشاهداً لك لا عليك! ⚖️", en: "May Allah make the Quran your intercessor and not a witness against you! ⚖️" },
  18: { ar: "«قَدْ أَفْلَحَ الْمُؤْمِنُونَ» أفلحت ورب الكعبة، استمر في تلاوتك! 🏆", en: "«Certainly will the believers have succeeded» You have succeeded, keep reading! 🏆" },
  19: { ar: "«وَقَالَ الَّذِينَ كَفَرُوا لَوْلَا نُزِّلَ عَلَيْهِ الْقُرْآنُ جُمْلَةً وَاحِدَةً» هكذا ثبّت الله فؤادك بالورد اليومي! 🌱", en: "This is how Allah strengthens your heart with a daily portion! 🌱" },
  20: { ar: "«فَمَا كَانَ جَوَابَ قَوْمِهِ» جوابك كان التلاوة المستمرة! الجزء العشرون اكتمل 🥇", en: "Your response was continuous recitation! The twentieth Juz is complete 🥇" },
  21: { ar: "«وَلَا تُجَادِلُوا أَهْلَ الْكِتَابِ إِلَّا بِالَّتِي هِيَ أَحْسَنُ» حسن مسعاك، زادك الله نوراً! ✨", en: "Excellent endeavor, may Allah increase your light! ✨" },
  22: { ar: "«يَا أَيُّهَا النَّاسُ اتَّقُوا رَبَّكُمْ» بالقرآن تحيا القلوب! استمر يا بطل القرآن 💫", en: "With the Quran, hearts come alive! Keep going, champion of the Quran 💫" },
  23: { ar: "«وَمَا أَنزَلْنَا عَلَى قَوْمِهِ مِن بَعْدِهِ مِن جُندٍ مِّنَ السَّمَاءِ» إنما نزلت السكينة تتنزل عليك الآن! 🕊️", en: "Tranquility is descending upon you now! 🕊️" },
  24: { ar: "«فَمَنْ أَظْلَمُ مِمَّن كَذَبَ عَلَى اللَّهِ» ومن أصدق منك وأنت تقرأ كتاب الحق! الجزء الرابع والعشرون 🌹", en: "And who is more truthful than you reading the Book of Truth! The twenty-fourth Juz 🌹" },
  25: { ar: "«إِلَيْهِ يُرَدُّ عِلْمُ السَّاعَةِ» رفع الله درجتك بكل حرف تلوته ⏳", en: "May Allah elevate your status with every letter you recited ⏳" },
  26: { ar: "«حم * تَنزِيلُ الْكِتَابِ مِنَ اللَّهِ الْعَزِيزِ الْحَكِيمِ» الحكمة تجري على لسانك بتلاوتك! 🌟", en: "Wisdom flows on your tongue with your recitation! 🌟" },
  27: { ar: "«قَالَ فَمَا خَطْبُكُمْ أَيُّهَا الْمُرْسَلُونَ» رسا قلبك على شواطئ الختمة، اقتربت! ⛵", en: "Your heart has anchored on the shores of completion, you are getting closer! ⛵" },
  28: { ar: "«قَدْ سَمِعَ اللَّهُ قَوْلَ الَّتِي تُجَادِلُكَ فِي زَوْجِهَا» الجزء المجادل! رفع الله قدرك 🌸", en: "The Juz of Al-Mujadila! May Allah elevate your destiny 🌸" },
  29: { ar: "«تَبَارَكَ الَّذِي بِيَدِهِ الْمُلْكُ» بارك الله لك، جزء تبارك يضيء قبرك وحياتك! 🕯️", en: "«Blessed is He in whose hand is dominion» Juz Tabarak illuminates your life! 🕯️" },
  30: { ar: "«عَمَّ يَتَسَاءَلُونَ» ختامها مسك! أتممت القرآن العظيم فهنيئاً لك شفاعته 💖", en: "«About what are they asking one another?» The absolute best conclusion! You completed the Quran 💖" }
};
